#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Define bash colours
NOCOLOR='\e[0m'
LIGHTRED='\e[1;31m'
YELLOW='\e[1;33m'
CYAN='\e[0;36m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEAST_HOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e FEEDER_ID"
if [ -z "${FEEDER_ID}" ]
then
  echo ""
  echo "WARNING: FEEDER_ID environment variable was not set!"
  echo "Please make sure you note down the key generated."
  echo "Pass the key as environment var FEEDER_ID on next launch!"
  echo ""
fi
# All is good ?
if [ $EXITCODE == 0 ]; then
  # shellcheck disable=SC2153
  echo -e "${CYAN}INFO: Connect to ${BEAST_HOST}:${BEAST_PORT} ${NOCOLOR}"
fi

exit $EXITCODE
