#!/usr/bin/with-contenv bash
# shellcheck shell=bash

sed -i -e "/^receiver-host.*/c\receiver-host ${BEAST_HOST}" /etc/piaware.conf
sed -i -e "/^receiver-port.*/c\receiver-port ${BEAST_PORT}" /etc/piaware.conf

sed -i -e "/^feeder-id/d" /etc/piaware.conf
if [ -n "${FEEDER_ID}" ]; then
  sed -i -e "/^receiver-port.*/a feeder-id ${FEEDER_ID}" /etc/piaware.conf
fi
