#!/usr/bin/with-contenv bash
# shellcheck shell=bash

sed -i -e "/^receiver-host.*/c\receiver-host ${BEAST_HOST}" /etc/piaware.conf
sed -i -e "/^receiver-port.*/c\receiver-port ${BEAST_PORT}" /etc/piaware.conf
